services:
  - type: web
    name: contact-book-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn contactbook.wsgi:application"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: contact-book-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False

databases:
  - name: contact-book-db
    plan: free
